apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversaotemperatura
spec:
   replicas: 3
   selector:
     matchLabels:
       app: conversaotemperatura
   template:
     metadata:
       labels:
         app: conversaotemperatura
     spec:
       containers:
         - name: conversaotemperatura
           image: luismartorano/conversaotemperaturav2:latest
           ports:
             - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: conversaotemperatura
spec: 
  selector: 
    app: conversaotemperatura
  ports:
    - port: 9080
      targetPort: 8080
      protocol: TCP
      name: http
      #nodePort: 30000
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: conversaotemperatura
  annotations:
    kubernetes.io/ingress.class: "nginx"

spec: 
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: conversaotemperatura
            port:
              number: 8080
      
